### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by BavoVC** [lrholmes/spotify-connect-ws#4]
I get no respons when initiating with an accessToken. However my connection to te server works with no problem.
`    
const socket = io('http://localhost:3002/connect');

    socket.on('connect', () => {
        console.log(socket.connected); // true
      });

    socket.on('disconnect', (reason) => {
    if (reason === 'io server disconnect') {
        // the disconnection was initiated by the server, you need to reconnect manually
        socket.connect();
    }else {
        console.log('Automatic reconecting');
    }
    // else the socket will automatically try to reconnect
    });

    socket.on('ping', () => {
        console.log('ping');
    });

    socket.on('pong', (latency) => {
        console.log('pong ' + latency);
    });

    socket.on('error', (error) => {
        console.log(error);
      });

       socket.emit('initiate', { accessToken: 'BQBb9FojdlAn3qFaOrDjI8NEuzzH9RzSmCtHrhQoFE0Uxkm2SBcXvBpo5iToIyz3O3YKq4DcobfxpO0-VWP8uXld-D_9UHkX1S-iFmhEsw6w_BckPMX2LrHgZZ_WkEFwBl0HuUa49Hu5VE5F5p2S0iaAipKucWcGyWqT-G7A7WyfKIk' })

    socket.on('initial_state', state => {
        console.log("test");
      })`

**Comment by lrholmes** [comment]
Sounds weird! I have a few ideas we can try to debug this, because - and don't be freaked out - but seeing as you provided your access token I tried it at the example page (https://spotify-connect-ws.netlify.com/) and it worked. So I'm guessing the error is with your server setup.

1.  Can you start logging `connect_error` as well? See if that returns anything.
2. Can you check your server console for errors?
3. Also, it might be an idea to try connecting to the example server just to rule out any client side issues (https://spotify-connect-ws.herokuapp.com/connect)

Give those things a try and let me know what comes up!

**Comment by BavoVC** [comment]
It works, thanks for the help!
